fx_version 'cerulean'
game 'gta5'
author 'Syntax'
description 'a standalone script that allows you to turn off all HUD elements in GTA 5.'
version '0.1'
client_script 'client/components.lua'
client_script 'config.lua'
